spring:
  application:
    name: BrakOffPC
  main:
    headless: true
  web:
    error:
      whitelabel:
        enabled: false
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    org.wodrol.brakoffpc: INFO

app:
  sqlite:
    path: ""
  ocr:
    pdftoppm-command: pdftoppm
    tesseract-command: tesseract
    language: pol+eng
    page-segmentation-mode: 6
    dpi: 400
